##
## Perform an Anlysis of data generated by this study: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
## all files originate from: http://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI HAR Dataset.zip
## the timestamp showing on the file at the time of download was "10-Dec-2012 02:05".
##
## The objective is to combine the study's training and test data into a single "tidy" data set with meaningful column names
##
## required packages: reshape2
##
run_analysis <- function() {
    
    ## read the training and test files
    trnData <- read.table("./UCI HAR Dataset/train/X_train.txt")
    tstData <- read.table("./UCI HAR Dataset/test/X_test.txt")
    
    ## combine the training and test data 
    allData <- rbind(trnData, tstData) #### (((This satisfies Part 1 of the Project)))
    
    ## read in the meaningful column name data
    colData <- read.table("./UCI HAR Dataset/features.txt")
    
    ## assign the values in colData to be the column names of the columns in allData
    colnames(allData) <- colData$V2 #### (((This satisfies Part 4 of the Project)))
    
    ## retain only mean and standard deviation data; (we include "mean frequency" also)
    colsToRetain <- colData$V2[grep("*mean\\(\\)|std\\(\\).*",colData$V2)]
    subData <- allData[colsToRetain] #### (((This satisfies Part 2 of the Project)))

    ## add test/train activity information
    trnActivity <- read.table("./UCI HAR Dataset/train/y_train.txt")
    tstActivity <- read.table("./UCI HAR Dataset/test/y_test.txt")
    ## combine train and test activity data... (rbind must be in the same order as above)
    allActivity <- rbind(trnActivity,tstActivity)
    ## replace activity as a number with activity as a description
    activityDesc <- read.table("./UCI HAR Dataset/activity_labels.txt")
    allActivityDesc <- as.data.frame(activityDesc$V2[allActivity$V1])
    colnames(allActivityDesc) <- c("Activity")
    ## add to our overall subset
    subData <- cbind(allActivityDesc,subData) #### (((This satisfies Part 3 of the Project)))
    
    ## add test/train subject information
    trnSubject <- read.table("./UCI HAR Dataset/train/subject_train.txt")
    tstSubject <- read.table("./UCI HAR Dataset/test/subject_test.txt")
    ## combine train and test subject data... (rbind must be in the same order as above)
    allSubjects <- rbind(trnSubject,tstSubject)
    colnames(allSubjects) <- c("Subject")
    ## add to our overall subset
    subData <- cbind(allSubjects,subData)
    
    ## Creates a data set with the average of each variable for each activity and each subject.
    meltData <- melt(subData,id=c("Subject","Activity"))
    meanData <- dcast(meltData,Subject + Activity ~ variable, mean)
    
    ## output the new data set -- (((satisfies part 5 of the proejct)))
    write.csv(meanData,"./ProjectTidyData.txt",row.names=FALSE)
}
